### PR TITLE
fixed code example in DNS docs

### PR DESCRIPTION
**Pull request by gecampbell**

### CODE REVIEW

**Comment by jamiehannaford** [comment]
@gecampbell Hey! it would be cool to get rid of all these merge commits. would you mind following these steps:

1. `git rebase -i` will open up a file showing a brief recent history of your commits. By default, all of the merge commits will be left out.
2. without changing the file, save and close the file (`:x` in vim)
3. force push the changes back to your fork with `git push -f glen working`

I believe this should remove all of them. If not, I'll merge as is :smile: cc/ @smashwilson

**Comment by gecampbell** [comment]
I'm obviously doing something wrong:

    fatal: 'glen' does not appear to be a git repository
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

**Comment by jamiehannaford** [comment]
@gecampbell ah sorry I used `glen` as an example. you should replace it with the name of your fork's remote ref. if you're not sure what that is, you can list all your remote names with `git remote show`. "origin" is usually reserved for the main repository (`rackspace/php-opencloud` in this case) - you're looking for the name corresponding to `gecampbell/php-opencloud`

**Comment by gecampbell** [comment]
Actually, `origin` is my fork, and `upstream` is the Rackspace one. It says
that everything is up-to-date, but all those merges still show up.

On Mon, Feb 9, 2015 at 9:08 AM, Jamie Hannaford <notifications@github.com>
wrote:

> @gecampbell <https://github.com/gecampbell> ah sorry I used glen as an
> example. you should replace it with the name of your fork's remote ref. if
> you're not sure what that is, you can list all your remote names with git
> remote show. "origin" is usually reserved for the main repository (
> rackspace/php-opencloud in this case) - you're looking for the name
> corresponding to gecampbell/php-opencloud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackspace/php-opencloud/pull/535#issuecomment-73523749>
> .
>



-- 
*Glen Campbell*
http://www.glencampbell.co • @glenc

**Comment by smashwilson** [comment]
@gecampbell Ah - I think I was making a bad assumption about your branch setup. Try this, instead:

```bash
# If you're not there already
git checkout working

# Make sure you're up to date with the main repo.
git fetch upstream

# Rebase against an explicit ref.
git rebase -i upstream/working
```

You should only see the non-merge commit. Accept it to do the rebase, then `git push -f` to bring GitHub up to date. :sparkles:

If that doesn't work, we can either cherry-pick the commit you want by hand, or I can just submit it as a new PR.

**Comment by smashwilson** [comment]
lol Monday

**Comment by gecampbell** [comment]
ok, is that better?

**Comment by jamiehannaford** [comment]
@gecampbell thanks! :rocket:

**Pull request merged**
