### PR TITLE
Adding PHP7 to build matrix.

### PR DESCRIPTION
**Pull request by ycombinator**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
"7.0" would be a better idea btw.

**Comment by ycombinator** [comment]
@jamiehannaford I was waiting to do that until we had our first PHP7 failure and had a chance to investigate it.

**Comment by ycombinator** [comment]
The build seems to hang at a particular test. Also, one of the tests fails but we can't tell which one because the build hangs. See https://travis-ci.org/rackspace/php-opencloud/jobs/52221618.

I'm going to try and spin up a PHP 7 dev environment and investigate the failing test as well as the hanging test.

**Comment by ycombinator** [comment]
Marking this PR as work in progress until I can figure out why PHP 7 builds are failing and fix if possible.

**Comment by ycombinator** [comment]
I tried making php-opencloud work with PHP7 but couldn't. Any changes I needed to make it work would break with PHP 5.4. As such, after consultation with @jamiehannaford, I've decided to abandon this effort.

**Pull request closed without merging**
