### PR TITLE
Return array of DataObjects if such is requested.

### LINKED ISSUE #545: Possible to get DataObject from Guzzle response?
Hi there,

`OpenCloud\ObjectStore\Resource\Container::uploadObjects()` returns an array of Guzzle responses (in contrast to `uploadObject()` which returns a `DataObject`).

Is it possible to get the `DataObject` from a Guzzle response? I need to upload a batch of files, but then store each file's public URL.

### PR DESCRIPTION
**Pull request by ycombinator**
In #545, I provided a workaround for what the user was requesting. This PR provides a more robust solution.

Fixes #545.

Attn: @jamiehannaford

### CODE REVIEW

**Comment by jamiehannaford** [comment]
LGTM - not sure why Travis is taking so long...

**Comment by ycombinator** [comment]
@jamiehannaford I've made all the changes per the code review.

**Comment by jamiehannaford** [comment]
@ycombinator feel free to self-merge this when travis passes :+1:

**Comment by ycombinator** [comment]
Self-merging as Travis build has passed.

**Pull request merged**
